### ISSUE TITLE
Backend Development - Review Analyzer

### ISSUE THREAD

**Issue by junbread** [skkuse/2019spring_41class_team5#18]
This is an issue tracker for the review analyzer.

Result of the analysis process should be formatted as follows:
- item id
- review id
- title
- date
- author
- content
- reference
- original review score
- corrected review score
- keywords [ name, sentiment (positive or negative), magnitude ]
- importance (refer to this document, https://brunch.co.kr/@jakeyim/16)

**Comment by goldshakil** [comment]
*Added some controllers/Models/Services.

* Initialized HTTP request handlers

* Changed NLP  API to Stanford NLP

**Comment by goldshakil** [comment]
added library and created review model

**Comment by goldshakil** [comment]
added NLP sentiment and token annotator

**Comment by goldshakil** [comment]
Sentiment Terminal Test
![image](https://user-images.githubusercontent.com/48248272/58657304-eee73000-8358-11e9-8017-14ac0bb313d6.png)

**Comment by goldshakil** [comment]
Can't store the JSON format / java object.. help needed

**Comment by goldshakil** [comment]
Done Fixing the JSON Formatting, Sentence and word sentiment analysis

**Comment by goldshakil** [comment]
LEFT PARTS:
1) Integration with crawler
2) Rating calculation
3) Importance Calculation

**Comment by junbread** [comment]
Refined and finished
