### ISSUE TITLE
Requirement Document

### ISSUE THREAD

**Issue by junbread** [skkuse/2019spring_41class_team5#8]
Initial complete version - commit 23df6020c522a22e95eb6d96f0c8dc3a7bf73b5b

**Comment by junbread** [comment]
TODO
- [ ] Refine diagrams
- [ ] Add behavioral diagrams for each system
- [ ] Refine system requirements
- [ ] Add more description for introduction (system overview)
- [ ] Add more description for database requirements

**Comment by goldshakil** [comment]
Tasks Accomplished:

>  Completed diagrams:

- Finished Main writing including introduction
- Finished Functional + non Functional Requirements

> To do:

- Edit and fix grammar and the overall look
