### ISSUE TITLE
Design Specification

### ISSUE THREAD

**Issue by junbread** [skkuse/2019spring_41class_team5#9]
Initial outline - 4999e4aa313ea63c58600526f06ea38ef787cf13

**Comment by goldshakil** [comment]
added class and sequence diagrams for backend

**Comment by junbread** [comment]
commit ea83e244a4e24243a11cbba0f61dafc9b7e353c0
1. finish introduction
2. added block diagrams for system overall architecture
3. added class diagrams for frontend

**Comment by junbread** [comment]
finished protocol design

**Comment by goldshakil** [comment]
added description for web crawler class
